### ISSUE TITLE
spawn npm ENOENT on Windows

### ISSUE THREAD

**Issue by robross0606** [morficus/license-ls#6]
Getting a spawn error on Windows.  Probably need to use `npx` or `npm.cmd` instead.

**Comment by robross0606** [comment]
Another good option is to use [cross-spawn](https://www.npmjs.com/package/cross-spawn) instead.

**Comment by morficus** [comment]
I've also expanded the TravisCI testing matrix to cover multiple platforms to ensure sure cross-platform support is always present.
